### ISSUE TITLE
Search seems not to work correctly

### ISSUE THREAD

**Issue by Deadfire-** [sarna-net/sarna-issues#40]
**Describe the bug**
As described by csdavis on discord:

_Noticing a couple of things so far. First, for a term to come up in the search bar, you have to type it in exactly as it appears in the article title, capitalization included. I understand the importance of this when formatting text in articles, but in the search bar this is quite a bit annoying._

**To Reproduce**
Using the search bar type in anything

**Expected behavior**
Old behavior allowed for autocompete to work regardless of capitalization

**Screenshots**
![IMG_0799.png](https://github.com/user-attachments/assets/ec5b856f-6ee8-4c5b-b75a-e12d48b1dd12)

![IMG_0800.png](https://github.com/user-attachments/assets/3e64ebca-0f86-44bf-a8c6-3b4ac2aa3b29)

**Additional context**
May have to do with the fact we are still using the ancient and not actively maintained [Extension:SphinxSearch](https://mediawiki.org/wiki/Extension:SphinxSearch) and not a more modern (and much more used/supported) one like [Extension:CirrusSearch](https://mediawiki.org/wiki/Extension:CirrusSearch)

**Comment by Deadfire-** [comment]
crs_kain on the discord has noticed the same thing saying:

_I don’t know if this is me having the memory of a goldfish, or the sarna server migration, but I swear I remember being able to type a single lower case i and get the dropdown to pull up the IIC. Not even “iic” pulls it up, and searching it doesn’t take you directly to the page either._

![IMG_1134.png](https://github.com/user-attachments/assets/72716216-bf1c-487e-b556-f62828961d86)

![IMG_1133.png](https://github.com/user-attachments/assets/5954f5d4-79f4-4e79-a625-41c8470e6e00)

**Comment by nicjansma** [comment]
[Extension:TitleKey](https://www.mediawiki.org/wiki/Extension:TitleKey) was removed (somewhat accidentally) during the upgrade, which allows for cAsE InSeNsItIVe title searches.

Going to see if I can apply it.

**Comment by nicjansma** [comment]
Fixed via some updates to `Extension:SphinxSearch` I applied https://github.com/nicjansma/mediawiki-extensions-SphinxSearch

**Comment by nicjansma** [comment]
Changes:

* CaSe InSeNsItIvE searching now for the autocomplete
* I've enabled 'infix' searching so it's not just title prefix, but matches can be anywhere in the string
* The resulting Title matches now highligh the correct search terms (previously they were highlighting the word `title`)

**Comment by Deadfire-** [comment]
Search still not search page contents for things like exact wikicode used and seems to still only returns Page Tile and Page Text (that is the same as Page Title) results.

**Comment by nicjansma** [comment]
csdavis says:

>Don't know if it's related, but sometimes if I search for the exact page title (via copy paste), the wiki thinks I entered it in wrong.

![Image](https://github.com/user-attachments/assets/60afa3fb-8c1f-4437-955b-777721f61b07)

**Comment by nicjansma** [comment]
I believe this is working better now, checking with csdavis and @Deadfire- to verify.

**Comment by nicjansma** [comment]
Closing this as search index is generally fixed, but there is a follow-up in https://github.com/sarna-net/sarna-issues/issues/59
